id: flow_ingestion
namespace: avantages_sportifs

tasks:
  - id: for_each_file
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ trigger.files }}"
    tasks:
      - id: ingest
        type: io.kestra.plugin.docker.Run
        containerImage: avantages_sportifs_python:latest
        pullPolicy: NEVER
        networkMode: avantages_sportifs_avantages_network
        inputFiles:
          "{{ json(taskrun.value).name }}": "{{ json(taskrun.value).uri }}"
        commands:
          - python
          - /app/scripts/ingestion.py
          - "{{workingDir}}/{{ json(taskrun.value).name }}"
        env:
          POSTGRES_HOST: "{{secret('POSTGRES_HOST')}}"
          POSTGRES_USER: "{{secret('POSTGRES_USER')}}"
          POSTGRES_PASSWORD: "{{secret('POSTGRES_PASSWORD')}}"
          POSTGRES_DB: "{{secret('POSTGRES_DB')}}"

      - id: archive_file
        type: io.kestra.plugin.fs.local.Move
        from: "/inbox/{{ json(taskrun.value).name }}"
        to: "/archive/{{ execution.startDate | date('yyyyMMddHHmmss') }}_{{ json(taskrun.value).name }}"

triggers:
  - id: watch_inbox
    type: io.kestra.plugin.fs.local.Trigger
    from: /inbox
    interval: PT10S
    action: NONE