services:
  postgres:
    image: postgres:15
    container_name: avantages_postgres
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - avantages_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init_schema.sql:/docker-entrypoint-initdb.d/01_init_schema.sql
      - ./sql/init_config.sql:/docker-entrypoint-initdb.d/02_init_config.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kestra:
    image: kestra/kestra:latest
    container_name: avantages_kestra
    pull_policy: always
    env_file: .env
    user: "root"
    command: server standalone
    ports:
      - "8080:8080"
    networks:
      - avantages_network
    volumes:
      - kestra_data:/app/storage
      - ./inbox:/inbox
      - ./archive:/archive
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/avantages_sportifs
            driverClassName: org.postgresql.Driver
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
        kestra:
          server:
            basicAuth:
              enabled: false
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          queue:
            type: postgres
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
      SECRET_POSTGRES_USER: YXZhbnRhZ2VzX3VzZXI=
      SECRET_POSTGRES_PASSWORD: YXZhbnRhZ2VzX3Bhc3M=
      SECRET_POSTGRES_DB: YXZhbnRhZ2VzX3Nwb3J0aWZz
      SECRET_POSTGRES_HOST: YXZhbnRhZ2VzX3Bvc3RncmVz
    depends_on:
      postgres:
        condition: service_healthy

networks:
  avantages_network:
    driver: bridge

volumes:
  postgres_data:
  kestra_data: